version: '3'
services:
  task-insided:
    container_name: task-insided
    image: webdevops/php-nginx-dev:8.1
    restart: always
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: '172.17.0.1'
      #XDEBUG_CLIENT_HOST: 'host.docker.internal'
      XDEBUG_CLIENT_PORT: 9000
      XDEBUG_DISCOVER_CLIENT_HOST: 0
      XDEBUG_START_WITH_REQUEST: 'yes'
    ports:
      - "8080:80"
    volumes:
      - ./:/app:rw,cached
volumes:
  db_data: {}
